CREATE TABLE LIVE_MEETINGS(
    HORAINICIOSESIONZOOM DATETIME,
    HORAFINCLASE DATETIME,
    START_TIME DATETIME,
    PARTICIPANTESACTIVOS int CHECK(PARTICIPANTESACTIVOS>=0),
    CRN int,
    CLAVEEJERCICIOACADEMICO int,
    CORREOELECTRONICOPROFESOR varchar(255),
    UUID varchar(255),
    JOINURL varchar(255),
    TIMESTAMP_1 DATETIME,
    IND_CLASEINICIADA varchar(255),
    TIMESTAMP_PARTITION varchar(255)
)


CREATE TABLE SIMULADOR_DWH(
    HORAINICIOSESIONZOOM DATETIME,
    HORAFINCLASE DATETIME,
    START_TIME DATETIME,
    PARTICIPANTESACTIVOS int CHECK(PARTICIPANTESACTIVOS>=0),
    CRN int,
    CLAVEEJERCICIOACADEMICO int,
    CORREOELECTRONICOPROFESOR varchar(255),
    UUID varchar(255),
    JOINURL varchar(255),
    TIMESTAMP1 DATETIME,
    IND_CLASEINICIADA varchar(255),
)

CREATE TABLE STREAM_LANDING_TABLE(
    CORREO varchar(255), 
    UUID varchar(255), 
    CORREOLIKE varchar(255), 
    HORAINICIO DATETIME,
    EVENTTYPE varchar(255),
    JOINURL varchar(255)
)

CREATE TABLE MEETING_BEGINS(
    CORREO varchar(255), 
    UUID varchar(255), 
    CORREOLIKE varchar(255), 
    HORAINICIO DATETIME
)

CREATE TABLE MEETING_ENDS(
    UUID varchar(255)
)

CREATE TABLE PARTICIPANT_JOIN(
    UUID varchar(255)
)

CREATE TABLE PARTICIPANT_LEFT(
    UUID varchar(255)
)