CREATE PROCEDURE borrarTodosLiveMeetings
AS
DELETE FROM dbo.LIVE_MEETINGS
GO

CREATE PROCEDURE insertarClase @inicio_zoom DATETIME,@fin_clase DATETIME, @inicio_meeting DATETIME, @crn int, @term int, @correo varchar(255), @correolike varchar(255)
AS
IF EXISTS (SELECT * FROM dbo.LIVE_MEETINGS
    WHERE CORREOELECTRONICOPROFESOR LIKE @correolike AND UUID IS NOT NULL)
BEGIN
    INSERT INTO dbo.LIVE_MEETINGS (HORAINICIOSESIONZOOM, HORAFINCLASE, START_TIME, PARTICIPANTESACTIVOS, CRN, CLAVEEJERCICIOACADEMICO, CORREOELECTRONICOPROFESOR,
    UUID, JOINURL) 
    SELECT TOP 1 @inicio_zoom, @fin_clase, @inicio_meeting, PARTICIPANTESACTIVOS, @crn, @term, @correo, UUID,  JOINURL
    FROM dbo.LIVE_MEETINGS
    WHERE CORREOELECTRONICOPROFESOR LIKE @correolike AND UUID IS NOT NULL
    DELETE FROM dbo.LIVE_MEETINGS
    WHERE CORREOELECTRONICOPROFESOR LIKE @correolike AND HORAINICIOSESIONZOOM='12/31/2099 0:00:00'
END
ELSE 
BEGIN 
    INSERT INTO dbo.LIVE_MEETINGS (HORAINICIOSESIONZOOM, HORAFINCLASE, PARTICIPANTESACTIVOS, CRN, CLAVEEJERCICIOACADEMICO, CORREOELECTRONICOPROFESOR) 
    values (@inicio_zoom, @fin_clase, 0, @crn, @term, @correo)
END
GO

CREATE PROCEDURE eliminarClasesPasadas @hora_fin DATETIME
AS
DELETE FROM dbo.LIVE_MEETINGS 
WHERE HORAFINCLASE=@hora_fin and UUID IS NULL

UPDATE dbo.LIVE_MEETINGS
SET HORAINICIOSESIONZOOM='12/31/2099 0:00:00', HORAFINCLASE=NULL, CRN=NULL, CLAVEEJERCICIOACADEMICO=NULL
WHERE UUID IS NOT NULL AND HORAFINCLASE=@hora_fin AND UUID IN (SELECT UUID FROM dbo.LIVE_MEETINGS GROUP BY UUID HAVING COUNT(DISTINCT UUID) = 1 )

DELETE FROM dbo.LIVE_MEETINGS 
WHERE HORAFINCLASE=@hora_fin AND UUID IS NOT NULL AND UUID NOT IN (SELECT UUID FROM dbo.LIVE_MEETINGS GROUP BY UUID HAVING COUNT(DISTINCT UUID) = 1 )
GO


CREATE PROCEDURE insertarMeeting @correo varchar(255), @uuid varchar(255), @correolike varchar(255), @horainicio DATETIME, @joinurl varchar(255)
AS
IF EXISTS (SELECT * FROM dbo.LIVE_MEETINGS
            WHERE CORREOELECTRONICOPROFESOR LIKE @correolike)
BEGIN
    UPDATE dbo.LIVE_MEETINGS
    SET UUID=@uuid, PARTICIPANTESACTIVOS=0, START_TIME=@horainicio, JOINURL=@joinurl
    WHERE CORREOELECTRONICOPROFESOR LIKE @correolike AND UUID IS NULL
    --UPDATE dbo.LIVE_MEETINGS
    --SET UUID=@uuid, START_TIME=@horainicio, JOINURL=@joinurl
    --WHERE CORREOELECTRONICOPROFESOR LIKE @correolike AND UUID IS NOT NULL
END
ELSE
BEGIN
    INSERT INTO dbo.LIVE_MEETINGS (HORAINICIOSESIONZOOM, START_TIME, CORREOELECTRONICOPROFESOR, PARTICIPANTESACTIVOS, UUID, JOINURL) values ('12/31/2099 0:00:00', @horainicio, @correo,0, @uuid, @joinurl)
END
GO

CREATE PROCEDURE borrarMeeting @uuid varchar(255)
AS
    DELETE FROM dbo.LIVE_MEETINGS
    WHERE UUID=@uuid AND HORAINICIOSESIONZOOM ='12/31/2099 0:00:00'
    UPDATE dbo.LIVE_MEETINGS
    SET PARTICIPANTESACTIVOS=0, UUID=NULL, JOINURL=NULL
    WHERE UUID=@uuid
GO

CREATE PROCEDURE agregarParticipante @uuid varchar(255)
AS
    UPDATE dbo.LIVE_MEETINGS
    SET PARTICIPANTESACTIVOS=PARTICIPANTESACTIVOS+1
    WHERE UUID=@uuid
GO

CREATE PROCEDURE quitarParticipante @uuid varchar(255)
AS
    UPDATE dbo.LIVE_MEETINGS
    SET PARTICIPANTESACTIVOS=PARTICIPANTESACTIVOS-1
    WHERE UUID=@uuid AND PARTICIPANTESACTIVOS>0
GO

CREATE PROCEDURE updateColumnasDWH
AS
    DECLARE @fecha DATETIME
    DECLARE @fechaStr varchar(255)
    SELECT @fecha=GETUTCDATE()
    SELECT @fechaStr=CONVERT(varchar(10), DATEPART ( YEAR , @fecha  )) +'-'+CONVERT(varchar(10), DATEPART ( MONTH , @fecha  ))+'-'+CONVERT(varchar(10), DATEPART ( DAY , @fecha  ))+'-'+CONVERT(varchar(10), DATEPART ( HOUR , @fecha  ))+'-'+CONVERT(varchar(10), DATEPART ( MINUTE , @fecha  ))
    UPDATE dbo.LIVE_MEETINGS
    SET IND_CLASEINICIADA='Si'
    WHERE PARTICIPANTESACTIVOS>0
    UPDATE dbo.LIVE_MEETINGS
    SET IND_CLASEINICIADA='No'
    WHERE PARTICIPANTESACTIVOS=0
    UPDATE dbo.LIVE_MEETINGS
    SET  TIMESTAMP_PARTITION = @fechaStr, TIMESTAMP_1 = @fecha
    SELECT * FROM dbo.LIVE_MEETINGS WHERE HORAINICIOSESIONZOOM <'12/31/2099 0:00:00'
GO

